# Configure and deploy Apache

- name: provision instance for Apache
  hosts: localhost
  connection: local
  remote_user: ubuntu
  gather_facts: false
  vars_files:
    - vars/env.yml
  vars:
    key_name: ansible-test
    region: us-east-2
    image: ami-0e82959d4ed12de3f # Ubuntu 18.04
    id: "practice42"
    sec_group: "{{ id }}-sec"
  roles:
    - aws

- name: Sets up the project
  hosts: launched
  remote_user: ubuntu
  become: yes
  vars:
    project_root_dir: "/srv/Practice"
    ssh_git_repo_url: "git@github.com:yii2-starter-kit/yii2-starter-kit.git"
    ssh_key_path: ~/.ssh/id_rsa
    ansible_ssh_private_key_file: "~/.ssh/ansible-test"
    mysql_root_password: password
    host_user: ubuntu
    http_host: practice57.plts.in
    project_name: Practice
  roles:
    - setup