# Download mysql debian package
- name: Install MySQL
  apt:
    name: mysql-server
    update_cache: yes
    state: present
  notify:
      - Start MySQL

- name: install pip3
  apt: name=python3-pip state=present 

- name: Install pip
  apt:
    name: python-pip
    update_cache: yes
    state: present

- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  pip:
    name: pymysql
    state: present
# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT  login_unix_socket=/var/run/mysqld/mysqld.sock
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: copy .my.cnf file with root password credentials
  template: src=./../../templates/.my-credentials.cnf.j2 dest=/root/.my.cnf owner=root mode=0600