- name: Sets Nginx conf file
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ project_name }}.conf"

- name: Enables new site
  file:
    src: "/etc/nginx/sites-available/{{ project_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    state: link
  notify: Reload Nginx

- name: Removes "default" site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx