- name: "Install Nginx and PHP"
  apt:
    pkg:
      - nginx
      - php
      - unzip
      - php-curl
      - php-gd
      - php-intl
      - php-mysql
      - php-xml
      - php-zip
      - php-soap
      - php-mbstring
      - php-cli
      - php-fpm
    state: present

